# CSV 파일로 데이터 다루기

- csv 데이터 알아보기
- 파이썬으로 csv 파일 읽고 쓰기
- csv파일 안의 문자를 숫자로 전환하기
- csv 파일로 데이터 분석하기

- csv (comma Separated Value): 쉼표(,)로 데이터를 분류
- 엑셀처럼 표로 볼 수 있는 데이터

In [15]:
import csv,os,codecs
os.chdir('/Users/gimtaehun/day1102')

f = codecs.open('a.csv' , 'r', encoding='cp949')
new = csv.reader(f)
a_list = []
for i in new:
    #print(i)
    a_list.append(i)
    
f.close()

print(a_list)

[['국어', '영어', '수학'], ['90', '80', '100']]

In [18]:
def opencsv(filename):
    f = open(filename, 'r', encoding='cp949')
    reader = csv.reader(f)
    output = []
    for i in reader:
        output.append(i)
    f.close()
    return output
print(opencsv('a.csv'))

[['국어', '영어', '수학'], ['90', '80', '100']]

In [8]:
#csv형식의 파이썬 리스트

a= [['구','전체','내국인','외국인'],
['서초구','169518','411515','407672'],
['강남구','234885','536710','531777'],
['송파구','286119','668638','662961'],
['강동구','202861','465496','461630']]

f = open('abc.csv' , 'w', newline = '')

csvobject = csv.writer(f, delimiter = ',')
csvobject.writerows(a)
f.close()

In [36]:
def writecsv(filename, the_list):
    with open(filename, 'w', newline = '')
    a = csv.writer(f, delimiter = ',')
    a.writerows(the_list)

SyntaxError: invalid syntax (593377403.py, line 2)

In [20]:
import usecsv

total = usecsv.opencsv("iseoulu.csv")
for i in total[:5]:
    print(i)

['동별(2)', '2022 3/4', '2022 3/4', '2022 3/4']
['동별(2)', '한국인', '등록외국인', '65세이상고령자']
['소계', '9,450,768', '231,358', '1,650,367']
['구로구', '393,181', '23,389', '75,041']
['영등포구', '376,216', '22,722', '64,285']

In [28]:
# 쉼표 제거하기

import re
i = total[5]
k = []
for j in i:
    if re.search('\d', j):
        k.append(float(re.sub(',','',j)))
        
    else:
        k.append(j)
k

['동대문구', 337106.0, 16075.0, 63807.0]

In [29]:
i = ['123!!', '151,767' , '11,093', '27,394' , '']

for j in i:
    try:
        i[i.index(j)] = float(re.sub(',', '',j))
    except:
        pass
i

['123!!', 151767.0, 11093.0, 27394.0, '']

In [33]:
# , 를 공백으로 바꾸는 
import re
i = ['120!!' , '123,456', '' ,'!!22$%']
for j in i:
    try:
        i[i.index(j)] = float(re.sub(",",'',j))
    except:
        pass
print(i)

['120!!', 123456.0, '', '!!22$%']

In [64]:
import usecsv

total = usecsv.opencsv('iseoulu.csv')
newPop = usecsv.switch(total)
print(newPop[:4])

[['동별(2)', '2022 3/4', '2022 3/4', '2022 3/4'], ['동별(2)', '한국인', '등록외국인', '65세이상고령자'], ['소계', 9450768.0, 231358.0, 1650367.0], ['구로구', 393181.0, 23389.0, 75041.0]]

In [74]:
#외국인 비율 구하기
#i = newPop[1]
print(len(newPop))
for i in newPop:
    foreign = 0
    try: 
        foreign = round (i[2]/(i[1]+i[2]) * 100, 1)
    except TypeError:
        pass
    print(i[0], foreign)

28
동별(2) 0
동별(2) 0
소계 2.4
구로구 5.6
영등포구 5.7
동대문구 4.6
용산구 6.2
관악구 2.8
금천구 5.5
광진구 3.7
서대문구 3.8
마포구 2.9
성북구 2.4
종로구 6.6
중구 7.5
동작구 2.3
성동구 2.3
송파구 0.8
강서구 0.9
강남구 0.9
중랑구 1.2
노원구 0.8
서초구 1.0
강동구 0.8
은평구 0.8
강북구 1.3
양천구 0.7
도봉구 0.7

In [57]:
new = [['구', '한국인', '외국인', '외국인비율(%)']]

for i in newPop:
    foreign = 0
    try:
        foreign = round(i[2]/(i[1]+i[2])*100 ,1)
        if foreign >3:
            new.append([i[0],i[1],i[2], foreign])
            
    except:
        pass
usecsv.writecsv("newPop.csv" , new)

In [84]:
#부동산 거래 매물
import usecsv

apt = usecsv.switch(usecsv.opencsv("op1.csv"))
print(apt[:3])

[['시군구', '번지', '본번', '부번', '단지명', '전용면적(㎡)', '계약년월', '계약일', '거래금액(만원)', '층', '건축년도', '도로명', '해제사유발생일', '거래유형', '중개사소재지'], ['서울특별시 강남구 개포동', '13-3', 13.0, 3.0, '대청타워', 32.44, 202210.0, 13.0, 20650.0, 5.0, 1997.0, '개포로 623', '', '직거래', '-'], ['서울특별시 강남구 대치동', '890-59', 890.0, 59.0, '선릉역 롯데골드로즈2', 44.46, 202210.0, 14.0, 41700.0, 16.0, 2004.0, '선릉로86길 31', '', '중개거래', '서울 강남구']]

In [120]:
import re
for i in apt:
    try:
        if i[6] > 30 and i[8] >= 3000 and re.match("서울" , i[0]) and i[10] > 2004:
            print(i[0]+'/',int(i[5]),"㎡",int(i[8]),"만원",int(i[10]),"년")
    except:
        pass

서울특별시 강남구 세곡동/ 24 ㎡ 22900 만원 2016 년
서울특별시 강남구 역삼동/ 26 ㎡ 48128 만원 2020 년
서울특별시 강남구 역삼동/ 28 ㎡ 41400 만원 2018 년
서울특별시 강남구 역삼동/ 31 ㎡ 26500 만원 2012 년
서울특별시 강남구 역삼동/ 23 ㎡ 31500 만원 2015 년
서울특별시 강남구 역삼동/ 24 ㎡ 32000 만원 2015 년
서울특별시 강남구 역삼동/ 22 ㎡ 26800 만원 2014 년
서울특별시 강남구 역삼동/ 17 ㎡ 28000 만원 2019 년
서울특별시 강남구 역삼동/ 29 ㎡ 23000 만원 2005 년
서울특별시 강남구 역삼동/ 20 ㎡ 15800 만원 2006 년
서울특별시 강남구 역삼동/ 20 ㎡ 15800 만원 2006 년
서울특별시 강남구 역삼동/ 18 ㎡ 19500 만원 2013 년
서울특별시 강남구 역삼동/ 20 ㎡ 20500 만원 2013 년
서울특별시 강남구 자곡동/ 21 ㎡ 17950 만원 2014 년
서울특별시 강남구 자곡동/ 25 ㎡ 19000 만원 2014 년
서울특별시 강남구 자곡동/ 25 ㎡ 19000 만원 2014 년
서울특별시 강남구 자곡동/ 32 ㎡ 32700 만원 2018 년
서울특별시 강남구 청담동/ 58 ㎡ 149000 만원 2018 년
서울특별시 강동구 강일동/ 28 ㎡ 11000 만원 2013 년
서울특별시 강동구 명일동/ 19 ㎡ 19000 만원 2020 년
서울특별시 강동구 천호동/ 23 ㎡ 30000 만원 2021 년
서울특별시 강동구 천호동/ 25 ㎡ 17400 만원 2015 년
서울특별시 강동구 천호동/ 25 ㎡ 19400 만원 2015 년
서울특별시 강동구 천호동/ 26 ㎡ 19000 만원 2015 년
서울특별시 강동구 천호동/ 23 ㎡ 14700 만원 2013 년
서울특별시 강북구 수유동/ 34 ㎡ 11400 만원 2005 년
서울특별시 강북구 수유동/ 28 ㎡ 11600 만원 2005 년
서울특별시 강서구 가양동/ 28 ㎡ 28300 만원 2018 년
서울특별시 강서구 공항동/ 24 ㎡ 12000 만원 2011 년
서울특별시 강서구 등촌동/ 57 ㎡ 37000 만원 2005 년
서울특별시 강서구 마곡동/ 26 ㎡ 25000 만원 2019 년
서울특별시 강서구 마곡동/ 24 ㎡ 16700 만원 2015 년
서울특별시 강서구 마곡동/ 24 ㎡ 16000 만원 2015 년
서울특별시 강서구 마곡동/ 29 ㎡ 18600 만원 2015 년
서울특별시 강서구 마곡동/ 19 ㎡ 18500 만원 2017 년
서울특별시 강서구 마곡동/ 19 ㎡ 16500 만원 2017 년
서울특별시 강서구 마곡동/ 22 ㎡ 21900 만원 2017 년
서울특별시 강서구 마곡동/ 30 ㎡ 30900 만원 2016 년
서울특별시 강서구 마곡동/ 25 ㎡ 24100 만원 2016 년
서울특별시 강서구 마곡동/ 17 ㎡ 13000 만원 2015 년
서울특별시 강서구 마곡동/ 17 ㎡ 14500 만원 2015 년
서울특별시 강서구 마곡동/ 32 ㎡ 32500 만원 2017 년
서울특별시 강서구 마곡동/ 21 ㎡ 17500 만원 2017 년
서울특별시 강서구 마곡동/ 21 ㎡ 17500 만원 2017 년
서울특별시 강서구 마곡동/ 25 ㎡ 18000 만원 2016 년
서울특별시 강서구 마곡동/ 30 ㎡ 21500 만원 2016 년
서울특별시 강서구 마곡동/ 24 ㎡ 19800 만원 2017 년
서울특별시 강서구 마곡동/ 24 ㎡ 19700 만원 2017 년
서울특별시 강서구 마곡동/ 24 ㎡ 19300 만원 2017 년
서울특별시 강서구 마곡동/ 24 ㎡ 17900 만원 2016 년
서울특별시 강서구 마곡동/ 22 ㎡ 16900 만원 2016 년
서울특별시 강서구 마곡동/ 26 ㎡ 20000 만원 2016 년
서울특별시 강서구 마곡동/ 23 ㎡ 19000 만원 2016 년
서울특별시 강서구 마곡동/ 34 ㎡ 28800 만원 2015 년
서울특별시 강서구 마곡동/ 19 ㎡ 14200 만원 2015 년
서울특별시 강서구 마곡동/ 19 ㎡ 14000 만원 2015 년
서울특별시 강서구 마곡동/ 19 ㎡ 14600 만원 2015 년
서울특별시 강서구 마곡동/ 20 ㎡ 15000 만원 2015 년
서울특별시 강서구 마곡동/ 20 ㎡ 14800 만원 2015 년
서울특별시 강서구 마곡동/ 17 ㎡ 13400 만원 2016 년
서울특별시 강서구 마곡동/ 23 ㎡ 18500 만원 2015 년
서울특별시 강서구 마곡동/ 19 ㎡ 14000 만원 2015 년
서울특별시 강서구 마곡동/ 22 ㎡ 16300 만원 2016 년
서울특별시 강서구 마곡동/ 20 ㎡ 19000 만원 2017 년
서울특별시 강서구 마곡동/ 25 ㎡ 21500 만원 2017 년
서울특별시 강서구 마곡동/ 23 ㎡ 18850 만원 2016 년
서울특별시 강서구 염창동/ 28 ㎡ 27400 만원 2018 년
서울특별시 강서구 화곡동/ 28 ㎡ 27100 만원 2020 년
서울특별시 강서구 화곡동/ 28 ㎡ 28500 만원 2020 년
서울특별시 강서구 화곡동/ 28 ㎡ 28300 만원 2020 년
서울특별시 강서구 화곡동/ 19 ㎡ 35300 만원 2022 년
서울특별시 강서구 화곡동/ 19 ㎡ 34300 만원 2022 년
서울특별시 강서구 화곡동/ 43 ㎡ 15200 만원 2013 년
서울특별시 강서구 화곡동/ 29 ㎡ 35900 만원 2021 년
서울특별시 강서구 화곡동/ 36 ㎡ 39900 만원 2022 년
서울특별시 관악구 봉천동/ 19 ㎡ 12000 만원 2012 년
서울특별시 관악구 봉천동/ 20 ㎡ 21000 만원 2022 년
서울특별시 관악구 봉천동/ 49 ㎡ 31000 만원 2005 년
서울특별시 광진구 광장동/ 29 ㎡ 16200 만원 2011 년
서울특별시 광진구 구의동/ 40 ㎡ 27000 만원 2006 년
서울특별시 광진구 중곡동/ 15 ㎡ 19300 만원 2020 년
서울특별시 광진구 화양동/ 16 ㎡ 15000 만원 2017 년
서울특별시 광진구 화양동/ 19 ㎡ 14500 만원 2013 년
서울특별시 광진구 화양동/ 18 ㎡ 25000 만원 2020 년
서울특별시 광진구 화양동/ 20 ㎡ 20500 만원 2019 년
서울특별시 구로구 고척동/ 29 ㎡ 30000 만원 2021 년
서울특별시 구로구 구로동/ 19 ㎡ 12400 만원 2015 년
서울특별시 구로구 구로동/ 19 ㎡ 11800 만원 2015 년
서울특별시 구로구 구로동/ 19 ㎡ 11900 만원 2015 년
서울특별시 구로구 구로동/ 28 ㎡ 18000 만원 2016 년
서울특별시 구로구 구로동/ 21 ㎡ 12500 만원 2012 년
서울특별시 구로구 구로동/ 18 ㎡ 11500 만원 2012 년
서울특별시 구로구 구로동/ 17 ㎡ 11800 만원 2013 년
서울특별시 구로구 구로동/ 17 ㎡ 12000 만원 2013 년
서울특별시 구로구 구로동/ 18 ㎡ 9700 만원 2011 년
서울특별시 구로구 구로동/ 25 ㎡ 13300 만원 2011 년
서울특별시 구로구 구로동/ 25 ㎡ 13500 만원 2011 년
서울특별시 구로구 구로동/ 25 ㎡ 14500 만원 2011 년
서울특별시 구로구 오류동/ 20 ㎡ 11500 만원 2017 년
서울특별시 구로구 오류동/ 17 ㎡ 15470 만원 2018 년
서울특별시 구로구 오류동/ 34 ㎡ 14000 만원 2005 년
서울특별시 구로구 오류동/ 17 ㎡ 17400 만원 2022 년
서울특별시 구로구 오류동/ 19 ㎡ 9500 만원 2014 년
서울특별시 금천구 가산동/ 17 ㎡ 14400 만원 2020 년
서울특별시 금천구 가산동/ 17 ㎡ 15500 만원 2020 년
서울특별시 금천구 가산동/ 17 ㎡ 11500 만원 2013 년
서울특별시 금천구 가산동/ 16 ㎡ 12500 만원 2017 년
서울특별시 금천구 가산동/ 16 ㎡ 11000 만원 2017 년
서울특별시 금천구 가산동/ 16 ㎡ 11000 만원 2017 년
서울특별시 금천구 가산동/ 17 ㎡ 15000 만원 2018 년
서울특별시 금천구 가산동/ 21 ㎡ 13400 만원 2013 년
서울특별시 금천구 가산동/ 17 ㎡ 10350 만원 2014 년
서울특별시 금천구 독산동/ 52 ㎡ 21500 만원 2014 년
서울특별시 금천구 독산동/ 27 ㎡ 19800 만원 2017 년
서울특별시 금천구 독산동/ 21 ㎡ 17500 만원 2019 년
서울특별시 금천구 독산동/ 20 ㎡ 17700 만원 2022 년
서울특별시 금천구 독산동/ 18 ㎡ 20000 만원 2017 년
서울특별시 금천구 독산동/ 55 ㎡ 44700 만원 2016 년
서울특별시 금천구 독산동/ 32 ㎡ 21000 만원 2016 년
서울특별시 금천구 독산동/ 16 ㎡ 17500 만원 2021 년
서울특별시 금천구 독산동/ 22 ㎡ 28000 만원 2021 년
서울특별시 금천구 시흥동/ 18 ㎡ 9500 만원 2012 년
서울특별시 노원구 상계동/ 36 ㎡ 16650 만원 2005 년
서울특별시 도봉구 도봉동/ 29 ㎡ 18000 만원 2017 년
서울특별시 도봉구 창동/ 26 ㎡ 24995 만원 2020 년
서울특별시 도봉구 창동/ 40 ㎡ 21000 만원 2014 년
서울특별시 동대문구 답십리동/ 23 ㎡ 15600 만원 2015 년
서울특별시 동대문구 답십리동/ 20 ㎡ 13800 만원 2015 년
서울특별시 동대문구 답십리동/ 20 ㎡ 13800 만원 2015 년
서울특별시 동대문구 답십리동/ 20 ㎡ 13250 만원 2015 년
서울특별시 동대문구 답십리동/ 31 ㎡ 24000 만원 2016 년
서울특별시 동대문구 답십리동/ 19 ㎡ 12500 만원 2016 년
서울특별시 동대문구 답십리동/ 19 ㎡ 13200 만원 2016 년
서울특별시 동대문구 용두동/ 18 ㎡ 10000 만원 2014 년
서울특별시 동대문구 용두동/ 36 ㎡ 16700 만원 2005 년
서울특별시 동대문구 용두동/ 39 ㎡ 19000 만원 2006 년
서울특별시 동대문구 용두동/ 39 ㎡ 17700 만원 2006 년
서울특별시 동대문구 장안동/ 29 ㎡ 26870 만원 2022 년
서울특별시 동대문구 장안동/ 21 ㎡ 11850 만원 2015 년
서울특별시 동대문구 장안동/ 21 ㎡ 11000 만원 2015 년
서울특별시 동대문구 전농동/ 19 ㎡ 13500 만원 2015 년
서울특별시 동대문구 휘경동/ 16 ㎡ 22666 만원 2020 년
서울특별시 동작구 사당동/ 18 ㎡ 16000 만원 2012 년
서울특별시 동작구 신대방동/ 20 ㎡ 15000 만원 2015 년
서울특별시 동작구 신대방동/ 20 ㎡ 16000 만원 2015 년
서울특별시 마포구 공덕동/ 27 ㎡ 26000 만원 2013 년
서울특별시 마포구 공덕동/ 31 ㎡ 24000 만원 2005 년
서울특별시 마포구 공덕동/ 23 ㎡ 33770 만원 2022 년
서울특별시 마포구 상암동/ 21 ㎡ 15500 만원 2016 년
서울특별시 마포구 상암동/ 21 ㎡ 15900 만원 2016 년
서울특별시 마포구 상암동/ 21 ㎡ 15900 만원 2016 년
서울특별시 마포구 상암동/ 24 ㎡ 16000 만원 2014 년
서울특별시 마포구 상암동/ 19 ㎡ 12000 만원 2013 년
서울특별시 마포구 상암동/ 19 ㎡ 11500 만원 2013 년
서울특별시 마포구 성산동/ 16 ㎡ 15000 만원 2018 년
서울특별시 마포구 성산동/ 16 ㎡ 13000 만원 2018 년
서울특별시 마포구 성산동/ 16 ㎡ 16000 만원 2018 년
서울특별시 마포구 성산동/ 17 ㎡ 22000 만원 2021 년
서울특별시 마포구 성산동/ 19 ㎡ 16500 만원 2017 년
서울특별시 마포구 성산동/ 24 ㎡ 15000 만원 2013 년
서울특별시 마포구 성산동/ 18 ㎡ 14000 만원 2016 년
서울특별시 마포구 성산동/ 16 ㎡ 16000 만원 2017 년
서울특별시 마포구 성산동/ 16 ㎡ 16700 만원 2018 년
서울특별시 마포구 성산동/ 19 ㎡ 13900 만원 2014 년
서울특별시 마포구 성산동/ 19 ㎡ 20500 만원 2019 년
서울특별시 마포구 신공덕동/ 18 ㎡ 17200 만원 2017 년
서울특별시 마포구 아현동/ 33 ㎡ 23000 만원 2006 년
서울특별시 마포구 합정동/ 25 ㎡ 35500 만원 2016 년
서울특별시 서대문구 대현동/ 18 ㎡ 14500 만원 2015 년
서울특별시 서대문구 대현동/ 18 ㎡ 15000 만원 2015 년
서울특별시 서대문구 대현동/ 15 ㎡ 21900 만원 2021 년
서울특별시 서대문구 대현동/ 19 ㎡ 18600 만원 2017 년
서울특별시 서대문구 대현동/ 20 ㎡ 18950 만원 2017 년
서울특별시 서대문구 대현동/ 20 ㎡ 20000 만원 2017 년
서울특별시 서대문구 대현동/ 17 ㎡ 20000 만원 2019 년
서울특별시 서대문구 대현동/ 15 ㎡ 16300 만원 2017 년
서울특별시 서대문구 북가좌동/ 43 ㎡ 31500 만원 2016 년
서울특별시 서대문구 연희동/ 28 ㎡ 30600 만원 2022 년
서울특별시 서대문구 연희동/ 29 ㎡ 31150 만원 2022 년
서울특별시 서대문구 연희동/ 29 ㎡ 31000 만원 2022 년
서울특별시 서대문구 창천동/ 17 ㎡ 23200 만원 2021 년
서울특별시 서초구 서초동/ 18 ㎡ 22400 만원 2017 년
서울특별시 서초구 서초동/ 38 ㎡ 39000 만원 2005 년
서울특별시 서초구 서초동/ 38 ㎡ 44500 만원 2005 년
서울특별시 서초구 서초동/ 30 ㎡ 20700 만원 2005 년
서울특별시 서초구 서초동/ 24 ㎡ 27500 만원 2016 년
서울특별시 서초구 서초동/ 15 ㎡ 13000 만원 2005 년
서울특별시 서초구 서초동/ 24 ㎡ 29300 만원 2013 년
서울특별시 서초구 서초동/ 20 ㎡ 21500 만원 2015 년
서울특별시 서초구 신원동/ 21 ㎡ 17550 만원 2015 년
서울특별시 서초구 우면동/ 27 ㎡ 21300 만원 2015 년
서울특별시 서초구 우면동/ 18 ㎡ 14000 만원 2015 년
서울특별시 서초구 우면동/ 18 ㎡ 14000 만원 2015 년
서울특별시 서초구 우면동/ 21 ㎡ 17000 만원 2015 년
서울특별시 서초구 우면동/ 22 ㎡ 17000 만원 2015 년
서울특별시 서초구 우면동/ 18 ㎡ 14000 만원 2015 년
서울특별시 성동구 성수동2가/ 15 ㎡ 35841 만원 2021 년
서울특별시 성동구 성수동2가/ 15 ㎡ 35841 만원 2021 년
서울특별시 성동구 용답동/ 48 ㎡ 20500 만원 2011 년
서울특별시 성동구 하왕십리동/ 27 ㎡ 17100 만원 2005 년
서울특별시 성동구 하왕십리동/ 22 ㎡ 15000 만원 2011 년
서울특별시 송파구 거여동/ 20 ㎡ 22000 만원 2022 년
서울특별시 송파구 문정동/ 25 ㎡ 25700 만원 2017 년
서울특별시 송파구 문정동/ 29 ㎡ 27600 만원 2015 년
서울특별시 송파구 문정동/ 49 ㎡ 75000 만원 2015 년
서울특별시 송파구 문정동/ 24 ㎡ 23100 만원 2013 년
서울특별시 송파구 문정동/ 30 ㎡ 26500 만원 2013 년
서울특별시 송파구 문정동/ 27 ㎡ 30000 만원 2013 년
서울특별시 송파구 문정동/ 29 ㎡ 25500 만원 2013 년
서울특별시 송파구 문정동/ 23 ㎡ 20700 만원 2013 년
서울특별시 송파구 문정동/ 20 ㎡ 22000 만원 2018 년
서울특별시 송파구 문정동/ 21 ㎡ 18100 만원 2017 년
서울특별시 송파구 문정동/ 21 ㎡ 17500 만원 2017 년
서울특별시 송파구 방이동/ 19 ㎡ 13500 만원 2013 년
서울특별시 송파구 오금동/ 55 ㎡ 37000 만원 2014 년
서울특별시 송파구 잠실동/ 24 ㎡ 29000 만원 2013 년
서울특별시 양천구 목동/ 18 ㎡ 13350 만원 2015 년
서울특별시 영등포구 당산동1가/ 29 ㎡ 31750 만원 2022 년
서울특별시 영등포구 당산동1가/ 24 ㎡ 26650 만원 2022 년
서울특별시 영등포구 당산동1가/ 26 ㎡ 28700 만원 2022 년
서울특별시 영등포구 당산동5가/ 23 ㎡ 23000 만원 2015 년
서울특별시 영등포구 양평동3가/ 29 ㎡ 26500 만원 2017 년
서울특별시 영등포구 양평동6가/ 28 ㎡ 36150 만원 2022 년
서울특별시 영등포구 양평동6가/ 28 ㎡ 36250 만원 2022 년
서울특별시 영등포구 양평동6가/ 28 ㎡ 36250 만원 2022 년
서울특별시 영등포구 영등포동1가/ 20 ㎡ 17000 만원 2013 년
서울특별시 영등포구 영등포동1가/ 19 ㎡ 22500 만원 2020 년
서울특별시 영등포구 영등포동2가/ 18 ㎡ 22000 만원 2018 년
서울특별시 영등포구 영등포동2가/ 14 ㎡ 14800 만원 2018 년
서울특별시 영등포구 영등포동7가/ 17 ㎡ 23500 만원 2021 년
서울특별시 영등포구 영등포동7가/ 40 ㎡ 25900 만원 2017 년
서울특별시 영등포구 영등포동8가/ 37 ㎡ 28000 만원 2017 년
서울특별시 용산구 문배동/ 21 ㎡ 25000 만원 2018 년
서울특별시 용산구 원효로2가/ 31 ㎡ 51400 만원 2022 년
서울특별시 은평구 불광동/ 23 ㎡ 26000 만원 2021 년
서울특별시 은평구 응암동/ 47 ㎡ 34900 만원 2021 년
서울특별시 은평구 응암동/ 56 ㎡ 36000 만원 2018 년
서울특별시 은평구 응암동/ 18 ㎡ 11500 만원 2014 년
서울특별시 은평구 진관동/ 24 ㎡ 13700 만원 2013 년
서울특별시 은평구 진관동/ 24 ㎡ 13900 만원 2013 년
서울특별시 은평구 진관동/ 45 ㎡ 34000 만원 2013 년
서울특별시 은평구 진관동/ 19 ㎡ 13000 만원 2017 년
서울특별시 은평구 진관동/ 19 ㎡ 12500 만원 2017 년
서울특별시 은평구 진관동/ 19 ㎡ 12600 만원 2017 년
서울특별시 은평구 진관동/ 19 ㎡ 13200 만원 2018 년
서울특별시 은평구 진관동/ 18 ㎡ 15000 만원 2017 년
서울특별시 은평구 진관동/ 23 ㎡ 12000 만원 2015 년
서울특별시 은평구 진관동/ 23 ㎡ 13400 만원 2015 년
서울특별시 은평구 진관동/ 26 ㎡ 13200 만원 2015 년
서울특별시 종로구 경운동/ 35 ㎡ 28900 만원 2005 년
서울특별시 종로구 숭인동/ 19 ㎡ 11000 만원 2014 년
서울특별시 종로구 숭인동/ 19 ㎡ 11100 만원 2014 년
서울특별시 종로구 숭인동/ 17 ㎡ 11000 만원 2013 년
서울특별시 종로구 숭인동/ 21 ㎡ 25500 만원 2022 년
서울특별시 종로구 숭인동/ 41 ㎡ 46000 만원 2022 년
서울특별시 종로구 숭인동/ 22 ㎡ 28500 만원 2022 년
서울특별시 종로구 신문로1가/ 41 ㎡ 47900 만원 2005 년
서울특별시 중구 을지로2가/ 35 ㎡ 34250 만원 2008 년
서울특별시 중구 충무로3가/ 37 ㎡ 29000 만원 2013 년
서울특별시 중구 황학동/ 29 ㎡ 40700 만원 2022 년
서울특별시 중구 황학동/ 29 ㎡ 40700 만원 2022 년
서울특별시 중구 황학동/ 29 ㎡ 37400 만원 2022 년
서울특별시 중구 황학동/ 19 ㎡ 12800 만원 2013 년
서울특별시 중구 흥인동/ 28 ㎡ 23000 만원 2014 년
서울특별시 중구 흥인동/ 25 ㎡ 21000 만원 2016 년
서울특별시 중랑구 망우동/ 17 ㎡ 9000 만원 2012 년
서울특별시 중랑구 망우동/ 17 ㎡ 8900 만원 2012 년
서울특별시 중랑구 망우동/ 17 ㎡ 11000 만원 2016 년

In [121]:
import re, usecsv	

English = 'She is a vegetarian. She does not eat meat. She thinks that animals should not be killed. It is hard for her to hang out with people. Many people like to eat meat. She told his parents not to have meat. They laughed at her. She realized they couldn\'t give up meat.'
## 영문을 English 객체에 저장합니다 
Korean = '그녀는 채식주의자입니다. 그녀는 고기를 먹지 않습니다. 그녀는 동물을 죽이지 말아야한다고 생각합니다. 그녀가 사람들과 어울리는 것은 어렵습니다. 많은 사람들이 고기를 좋아합니다. 그녀는 부모에게 고기를 먹지 말라고 말했습니다. 그들은 그녀를 비웃었다. 그녀는 그들이 고기를 포기할 수 없다는 것을 깨달았습니다. '
## 영문을 구글 번역기로 번역해 Korean 객체에 저장합니다 


Korean_list = re.split('\.', Korean)

English_list = re.split('\.',English)

print(Korean_list)


total = []

for i in range(len(English_list)):
	total.append([English_list[i], Korean_list[i]]	)

usecsv.writecsv('Korean_English.csv', total)

['그녀는 채식주의자입니다', ' 그녀는 고기를 먹지 않습니다', ' 그녀는 동물을 죽이지 말아야한다고 생각합니다', ' 그녀가 사람들과 어울리는 것은 어렵습니다', ' 많은 사람들이 고기를 좋아합니다', ' 그녀는 부모에게 고기를 먹지 말라고 말했습니다', ' 그들은 그녀를 비웃었다', ' 그녀는 그들이 고기를 포기할 수 없다는 것을 깨달았습니다', ' ']

In [123]:
import json
a = [1,2,3, {'4':5,'6':7}]
b = json.dumps(a) #파이썬 - > JSON
print(b)

c = json.loads(b) #JSON -> 파이썬
print(c)

[1, 2, 3, {"4": 5, "6": 7}]
[1, 2, 3, {'4': 5, '6': 7}]